[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
fs_permissions = [{ access = "read-write", path = "./"}]

[fuzz]
runs = 256

[profile.ffi]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
